### ISSUE TITLE
Cannot install on fluent-alpine docker container

### ISSUE THREAD

**Issue by rajiff** [moccos/fluent-plugin-websocket#5]
Hi

When i try installing this plugin on a fluent-alpine docker container, which is the official fluent container, the plugin fails to install with below error

The docker container used was https://hub.docker.com/r/fluent/fluentd/ 

```
gem install fluent-plugin-websocket
Building native extensions.  This could take a while...
ERROR:  Error installing fluent-plugin-websocket:
	ERROR: Failed to build gem native extension.

    current directory: /home/fluent/.gem/ruby/2.3.0/gems/eventmachine-1.2.0.1/ext
/usr/bin/ruby -r ./siteconf20160705-25-1tli78a.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /home/fluent/.gem/ruby/2.3.0/gems/eventmachine-1.2.0.1 for inspection.

```

**Comment by moccos** [comment]
Thank you for reporting. I'll check it after setting up dev environment for docker.

**Comment by moccos** [comment]
The header files are not installed in the container. You must install ruby header before installation.

```
/usr/lib/ruby $ ls
2.3.0        gems         vendor_ruby
```

[Offical document](https://hub.docker.com/r/fluent/fluentd/) says:

> Note: Default image removed several apk packages, build-base and ruby-dev, to keep docker image small. If you want to install the plugin which depends on native extension gems, needs to re-install these packages to build it.

**Comment by rajiff** [comment]
Thanks did installed, however this needed to run that in container as root, solved now

**Comment by khalilgharbaoui** [comment]
> Thanks did installed, however this needed to run that in container as root, solved now

@rajiff how did you finally run this as root in the container?
